### ISSUE TITLE
Style PositionPlacement ignores y percentage

### ISSUE THREAD

**Issue by afhp-2020** [fvwmorg/fvwm3#265]
Given the configuration line defined previously
```
Style volume-popup.script    PositionPlacement 0 75
```
the script window is expected to appear at the left of the screen (taking struts into account), 3/4 of the way down as it did previously. Instead, it appears at the top of the screen.

Changing the line (through FvwmConsole) to 
```
Style volume-popup.script    PositionPlacement 0 1000p
```
makes it appear where expected.

Modifying the x component (as a percentage, without suffix) behaves as expected.

version 1.0.1 (1.0.0-45-gb1072488)

**Comment by ThomasAdam** [comment]
Hi @afhp-2020 

Oh, good.  Looks like I've trampled over some previous value when shoe-horning in RandR.

Don't suppose you're up for submitting a patch to fix this, are you?  :)

**Comment by afhp-2020** [comment]
I'll give it a look, but no promises :) I'm not that much of a C developer. While I'm at it I should also give #40 a shot...

**Comment by ThomasAdam** [comment]
> I'll give it a look, but no promises :) I'm not that much of a C developer. While I'm at it I should also give #40 a shot...

Heh, thanks!  You don't need to be a C developer, just someone who has more of a brain than I do... ;)

As for #40 -- go for it!  I think I recall starting a pull-request to move things along with that, but since I'm generally ambivalent with how iconic window appear on different monitors for me, I've not really focused on revisiting my fix for that.  Selfish programming, eh?  :)

**Comment by afhp-2020** [comment]
Version `1.0.0-21-ge2c929d5` does not exhibit this bug, 1.0.1 release does.

**Comment by ThomasAdam** [comment]
Hi @afhp-2020 

Are you saying this is fixed?

**Comment by afhp-2020** [comment]
Hi Thomas, 

It is not fixed: things worked in a previous, 1.0.0 - level version, and are broken as of 1.0.1.

More specifically, bisecting for #264, it broke on
```
90f7b45841e534819ebe69232528613069217203 is the first bad commit
```
(both issues appear simultaneously)
