### ISSUE TITLE
EwmhBaseStruts glitch when using screen with different resolutions

### ISSUE THREAD

**Issue by lgsobalvarro** [fvwmorg/fvwm3#66]
EwmhBaseStruts glitches when using two or more screens with different resolutions.  FVWM3 will honor EwmhBaseStruts but only for the screen with the higher resolution available. EwmhBaseStruts will be ignored in all other screens.
[fvwm-1.log](https://github.com/fvwmorg/fvwm3/files/4578182/fvwm-1.log)

[fvwm.log](https://github.com/fvwmorg/fvwm3/files/4578204/fvwm.log)

**Comment by ThomasAdam** [comment]
Hi @lgsobalvarro,

Thanks for this report.

On the `ta/gh-66` branch, I've pushed some commits which means:

* `EWMHBaseStruts` command is now `screen` aware, which means you can do:  `EWMHBaseStruts screen NAME_OF_SCREEN a b c d` -- I will document this pending the conversation here.
  * Without setting per-screen `EWMHBaseStruts`, each monitor will inherit the setting
* Different monitor sizes should mean that maximiation of a window is respectful of any monitor resolution, plus `EWMHBaseStruts` setting.

Let me know whether this is working, or if it's utterly broken!

**Comment by lgsobalvarro** [comment]
It seems to be still broken.
I defined EWMHBaseStruts for eDP and HDMI-A-0 as follows:
EWMHBaseStruts screen eDP 0 68 0 62
EWMHBaseStruts screen HDMI-A-0 0 0 0 0

The issue is the window only "remebers" the latest EWMHBaseStruts. It ignores the first one. It does not matter in witch screen the window is located.
It does not matter if DesktopConfiguration is set as per-monitor or global.

I have also notice that if I maximize a window on eDP and then move it to HDMI-A-0 and then unmaximize, the window will return to eDP. I don't know if thise two issues are related to each other though.

**Comment by lgsobalvarro** [comment]
Log attached

[xorg-session (1).log](https://github.com/fvwmorg/fvwm3/files/4601571/xorg-session.1.log)

**Comment by ThomasAdam** [comment]
Hi @lgsobalvarro,

Please take another look at `ta/gh-66` and let me know if it's still not working.  :)

**Comment by lgsobalvarro** [comment]
It works now.

However I did notice this:

![2020-05-09-092058_1290x695_scrot](https://user-images.githubusercontent.com/1160397/81476319-040a4700-91d7-11ea-9237-368d4444c6f6.png)

Note that the window is maximized. The title bar does not refresh, is jsut stuck like that. It can be fixed by iconify and deiconify or by restarting fvwm3.

**Comment by lgsobalvarro** [comment]
xdpyinfo
[xdpyinfo.txt](https://github.com/fvwmorg/fvwm3/files/4603905/xdpyinfo.txt)

**Comment by ThomasAdam** [comment]
Thanks, @lgsobalvarro 

This is looking good, so I've merged it to master.  Please switch back to that branch, and report any problems.

I've now made unmaximizing windows track the change in monitor, if they're moved while maximizing, so this should behave better than it did before.

**Comment by lgsobalvarro** [comment]
This is an issue again for me since some time ago.

**Comment by ThomasAdam** [comment]
@lgsobalvarro 

Can you use `git bisect` to determine where I broke it?

**Comment by ThomasAdam** [comment]
Hi @lgsobalvarro 

Is this still an issue for you?  Anything I can do to reproduce this would be handy...

**Comment by lgsobalvarro** [comment]
Yes, this is still an issue.

I do not know... I can send you my config file again, of show it to you in action via jitsi or something.

**Comment by somiaj** [comment]
@lgsobalvarro Give that pull request a try. I think it fixes the problem (at least does in my tests).
